### ISSUE TITLE
[BUG] Wrong `offset` calculation

### ISSUE THREAD

**Issue by masardee** [halimtuhu/sequelize-typescript-paginator#1]
I am not tried the library yet, but when I read the code, I found something strange.
https://github.com/halimtuhu/sequelize-typescript-paginator/blob/6fba7842e95047e65b2dcb1c7069b2af1b742e0d/src/index.ts#L26

**Correct case**
```
meta.page = 2
meta.perPage = 10

// Expectation:
options.offset = 11

// Reality:
offset = (2 - 1) * (10 + 1) = 11
```

**Wrong case:**
```
meta.page = 3
meta.perPage = 10

// Expectation:
options.offset = 21

// Reality:
offset = (3 - 1) * (10 + 1) = 22
```

**So, I suggest this correction:**
```
options.offset = (meta.page - 1) * meta.perPage + 1;

// Simulation
meta.page = 3
meta.perPage = 10

// Expectation:
options.offset = 21

// Reality:
offset = (3 - 1) * 10 + 1 = 21
```

One thing, it's better if you write a test.

**Comment by halimtuhu** [comment]
Thank you for the review, I've pushed a new update to fix that bug. You can check it in this commit ec225eb.
